### ISSUE TITLE
Do not print stack trace for assertion error

### ISSUE THREAD

**Issue by Avinash9969** [rluba/hamjest#58]
While using asserthat method we get following error
"AssertionError: Status Code Verification
       Expected: "201"
            but: was "400"
           + expected - actual

           -400
           +201

           at ResponseValidator.verifyStatusCode (C:\xxxxx\xx.js:69:16)
           at Initialize.<anonymous> (C:\xxxxx\xx.js:113:24)"

Can we just print
"AssertionError: Status Code Verification
       Expected: "201"
            but: was "400"
           + expected - actual

           -400
           +201"

**Comment by rluba** [comment]
Hey! For me it’s often useful to see the line of the assert that failed. But you could add an option for suppressing the stack trace, if it bothers you.
